#Define the goal
geometry_msgs/PointStamped pos
int32 grasp_state
---
# is reached or not
bool is_reached
# where hand is to /arm_origin_link
geometry_msgs/Point moved
---
# Define a feedback message
float32 percent_complete
