controller_list:
  - name: fake_tinker_move_group_controller
    joints:
      - virtual_x_joint
      - virtual_y_joint
      - virtual_yaw_joint
      - arm_base_joint
      - shoulder_flexion_joint
      - elbow_joint
      - wrist_extension